# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'sedastrela/pages/page/picture')),
                ('page', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
