# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('place', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'sedastrela/events/event/picture')),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
